
name: Go
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Lint
      run: |
        go get golang.org/x/lint/golint
        golint ./...
    - name: Test
      run: go test -tags debugspy -coverprofile=coverage.txt -covermode=atomic ./...
    - name: Upload codecov coverage
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: false
        verbose: true
    - name: Build
      run: go build -v ./...